### ISSUE TITLE
您好，想问一下，执行train.py文件时出现这个错误是为什么呢

### ISSUE THREAD

**Issue by lssttxs** [yeyupiaoling/PaddlePaddle-SSD#2]
ValueError: (InvalidArgument) Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE (at /paddle/paddle/fluid/pybind/imperative.cc:74)

**Comment by yeyupiaoling** [comment]
@lssttxs 你安装了什么版本的PaddlePaddle。这个项目用的是1.8版本的
